server:
  port: ${PORT:8080}

spring:
  application:
    name: product-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.konrad: DEBUG
    root: WARN

konrad:
  mock:
    enabled: true
